name: ticktap
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # Local database
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  # Logging
  logger: ^1.1.0

  # Text
  auto_size_text: ^3.0.0

  # Widgets
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
